# Generated by Django 4.2.15 on 2024-09-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=1, max_digits=2),
        ),
    ]
