# Generated by Django 4.2.15 on 2024-09-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='pos',
            field=models.CharField(blank=True, choices=[('1', 'first'), ('2', 'second'), ('3', 'third')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='preview_for_index',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='pos',
            field=models.CharField(blank=True, choices=[('1', 'first'), ('2', 'second'), ('3', 'third'), ('4', 'fourth'), ('5', 'fifth')], default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='reklama',
            name='button_text_index',
            field=models.CharField(blank=True, default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='reklama',
            name='text_index',
            field=models.CharField(blank=True, default=None, max_length=80),
        ),
        migrations.AddField(
            model_name='reklama',
            name='tittle_index',
            field=models.CharField(blank=True, default=None, max_length=45),
        ),
        migrations.AddField(
            model_name='service',
            name='to_index',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='reklama',
            name='pos_reklama',
            field=models.CharField(choices=[('1', 'first'), ('2', 'second'), ('3', 'third'), ('4', 'index_popup')], max_length=1),
        ),
        migrations.AlterField(
            model_name='reklama',
            name='url',
            field=models.URLField(),
        ),
    ]
