# Generated by Django 4.2.15 on 2024-09-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='descr',
            field=models.CharField(blank=True, default='Description', max_length=128),
        ),
    ]
