# Generated by Django 4.2.15 on 2024-08-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apiuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='photo',
            field=models.ImageField(default=None, upload_to='media'),
        ),
    ]
