# Generated by Django 4.2.15 on 2024-09-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_article_is_draft_article_pos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reklama',
            name='pos_reklama',
            field=models.CharField(choices=[('1', 'first'), ('2', 'second'), ('3', 'third'), ('4', 'index_popup'), ('5', 'rotate1'), ('6', 'rotate2'), ('7', 'rotate3'), ('8', 'rotate4')], max_length=1),
        ),
    ]
