# Generated by Django 4.2.15 on 2024-09-12 20:03

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_article_image_alter_article_to_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='to_service',
        ),
        migrations.CreateModel(
            name='Obzor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('to_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.service')),
            ],
        ),
    ]
