# Generated by Django 4.2.15 on 2024-09-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_apiuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='photo',
            field=models.ImageField(default=None, upload_to='uploads/images/% Y/% m/% d/'),
        ),
    ]
