# Generated by Django 4.2.15 on 2024-09-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_apiuser_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reklama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default=None, upload_to='images/%Y/%m/%d/reklama')),
                ('url', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='photo',
            field=models.ImageField(default=None, upload_to='images/%Y/%m/%d/avatar'),
        ),
    ]
