# Generated by Django 4.2.15 on 2024-09-13 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_article_to_service_obzor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('perevod', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/preview'),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/%Y/%m/%d/partner')),
                ('descr', models.CharField(max_length=256)),
                ('promo', models.CharField(blank=True, default=None, max_length=64)),
                ('website', models.URLField(blank=True, default=None)),
                ('costs', models.CharField(blank=True, default=None, max_length=64)),
                ('category_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.category_partner')),
            ],
        ),
    ]
