# Generated by Django 4.2.15 on 2024-09-13 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_category_partner_alter_article_image_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obzor',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/obzor'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='category_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='api.category_partner'),
        ),
    ]
