# Generated by Django 4.2.15 on 2024-09-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_obzor_image_alter_partner_category_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
            preserve_default=False,
        ),
    ]
